name: Chip8 Emulator

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Build Essentials
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libsdl2-dev

      # 3. Compile the Program
      - name: Build the Test Program
        run: make -B
